// Generic Cloudflare Worker starter.
//
// Routes: GET /health only. Real apps add their own routes, auth, and
// bindings; see the README for what this template deliberately excludes.

import { AppError, errorResponse } from "./errors";

// `Env` is a global type generated by `wrangler types`
// (worker-configuration.d.ts); keep it in sync with wrangler.jsonc.

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    try {
      if (url.pathname === "/health" && request.method === "GET") {
        return Response.json({
          status: "ok",
          environment: env.ENVIRONMENT,
        });
      }
      throw new AppError("Not found", 404, "NOT_FOUND");
    } catch (err) {
      return errorResponse(err);
    }
  },
} satisfies ExportedHandler<Env>;
